import { eq } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { resources } from "@/lib/db/schema";
import { Chat } from "@/components/Chat";
import { isLlmConfigured, providerLabel } from "@/lib/ai/llm";

export const metadata = { title: "Ask the Library · Intimacy & Sex Therapy Library" };
export const dynamic = "force-dynamic";

export default async function ChatPage({
  searchParams,
}: {
  searchParams: Record<string, string | string[] | undefined>;
}) {
  const scopedResourceId =
    typeof searchParams.scope === "string" ? searchParams.scope : undefined;

  let scopedResourceTitle: string | undefined;
  if (scopedResourceId && process.env.DATABASE_URL) {
    const row = await db
      .select({ title: resources.title })
      .from(resources)
      .where(eq(resources.id, scopedResourceId))
      .limit(1);
    scopedResourceTitle = row[0]?.title;
  }

  const configured = isLlmConfigured();
  const provider = configured ? providerLabel() : null;

  return (
    <div className="container-page py-10 max-w-5xl">
      <header className="mb-6 max-w-2xl">
        <p className="pill-plum w-fit">Ask</p>
        <h1 className="mt-3 font-serif text-3xl sm:text-4xl text-ink-900">
          Ask the Library
        </h1>
        <p className="mt-2 text-ink-600">
          A chatbot grounded only in the curated corpus. Every claim is cited. If the
          library doesn&apos;t have an answer, it says so and stops.
        </p>
        <p className="mt-2 text-sm text-ink-400">
          Replies are generated by AI grounded in the curated library. Citations are shown
          for every claim. The AI can be wrong and is not a clinician.
        </p>
      </header>

      {!configured ? (
        <div
          role="status"
          className="mb-6 card p-4 text-sm border-warn/40"
        >
          <strong className="text-ink-900">Chatbot is disabled.</strong> No LLM provider
          is configured. Set <code>LLM_PROVIDER=groq</code> with{" "}
          <code>GROQ_API_KEY</code> (recommended for hosted deploys),{" "}
          <code>LLM_PROVIDER=anthropic</code> with <code>ANTHROPIC_API_KEY</code>, or{" "}
          <code>LLM_PROVIDER=ollama</code> with a reachable local Ollama daemon, then
          reload.
        </div>
      ) : (
        <div
          role="status"
          className="mb-6 card p-3 text-xs text-ink-400 flex items-center gap-2"
        >
          <span aria-hidden className="h-1.5 w-1.5 rounded-full bg-ok" />
          <span>
            Provider: <code className="text-ink-700">{provider}</code>
          </span>
        </div>
      )}

      <Chat
        scopedResourceId={scopedResourceId}
        scopedResourceTitle={scopedResourceTitle}
      />
    </div>
  );
}
