"use client";

/**
 * "Watch a 5-minute primer" — opens a calm, branded modal that plays the
 * homepage primer film (public/marketing/primer.mp4, regenerated by
 * marketing/primer/build_primer.py and the marketing-build workflow).
 *
 * Privacy-respecting by design: the video is self-hosted on our own origin —
 * no YouTube/Vimeo embed, no third-party tracking pixels, consistent with the
 * "no tracking" promise the film itself makes.
 */

import { useCallback, useEffect, useRef, useState } from "react";

const SRC = "/marketing/primer.mp4";
const POSTER = "/marketing/primer-poster.jpg";

export function PrimerModal({ className = "btn-secondary" }: { className?: string }) {
  const [open, setOpen] = useState(false);
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const closeRef = useRef<HTMLButtonElement | null>(null);

  const close = useCallback(() => {
    const v = videoRef.current;
    if (v) {
      v.pause();
      v.currentTime = 0;
    }
    setOpen(false);
  }, []);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") close();
    };
    document.addEventListener("keydown", onKey);
    // Lock background scroll while the dialog is up.
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    // Move focus into the dialog and try to autoplay.
    closeRef.current?.focus();
    videoRef.current?.play().catch(() => {});
    return () => {
      document.removeEventListener("keydown", onKey);
      document.body.style.overflow = prevOverflow;
    };
  }, [open, close]);

  return (
    <>
      <button type="button" className={className} onClick={() => setOpen(true)}>
        <span aria-hidden className="mr-1">▶</span> Watch a 5-minute primer
      </button>

      {open && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="A 5-minute primer about the Intimacy & Sex Therapy Library"
          className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-8"
          onClick={close}
        >
          <div aria-hidden className="absolute inset-0 bg-ink-900/70 backdrop-blur-sm" />
          <div
            className="relative w-full max-w-5xl animate-fade-up"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between gap-3 pb-3">
              <p className="text-sm text-white/90">
                A gentle 5-minute look — private by design.
              </p>
              <button
                ref={closeRef}
                type="button"
                onClick={close}
                aria-label="Close video"
                className="rounded-full bg-white/15 px-3 py-1.5 text-sm text-white hover:bg-white/25 transition-colors"
              >
                Close ✕
              </button>
            </div>
            <div className="overflow-hidden rounded-2xl shadow-2xl ring-1 ring-white/10 bg-black">
              <video
                ref={videoRef}
                src={SRC}
                poster={POSTER}
                controls
                playsInline
                preload="metadata"
                className="block w-full aspect-video"
              />
            </div>
          </div>
        </div>
      )}
    </>
  );
}
