import React from "react";
import {
  AbsoluteFill,
  Audio,
  OffthreadVideo,
  Sequence,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { BRAND, SAFE_AREA } from "./brand";
import type { StockSceneClip } from "./StockReel";

/**
 * 9:16 "narrator" reel. The persona avatar (a single talking-head MP4
 * generated by lib/social/avatar.ts) plays in the lower two-thirds of
 * the frame. The upper third carries kinetic typography for the hook,
 * each body scene, and the CTA. When a body scene has a stock B-roll
 * clip, we cut away from the avatar for that scene's duration while
 * the avatar's audio continues seamlessly underneath.
 *
 * The avatar MP4 is rendered MUTED and the voiceover is played as a
 * separate <Audio> track so the audio doesn't drop out during B-roll
 * cutaways.
 *
 * Falls back gracefully:
 *   - missing avatarUrl  -> warm radio-booth gradient with text only
 *   - missing voiceoverUrl -> silent (still usable for proofing)
 *   - missing clips      -> avatar stays visible for that scene
 */

export type AvatarReelScene = {
  text: string;
  seconds: number;
  clips: StockSceneClip[];
};

export type AvatarReelProps = {
  hook: string;
  scenes: AvatarReelScene[];
  cta: string;
  citationLine: string | null;
  language: "en" | "hi" | "hinglish";
  /** HTTPS URL of the avatar MP4 (returned by lib/social/avatar.ts). */
  avatarUrl: string | null;
  /** HTTPS URL of the voiceover MP3 (played as primary audio). */
  voiceoverUrl: string | null;
  totalSeconds: number;
};

const AVATAR_AREA_TOP = 672; // upper 35% reserved for text
const AVATAR_AREA_HEIGHT = 1248; // remaining 65%

export const AvatarReel: React.FC<AvatarReelProps> = ({
  hook,
  scenes,
  cta,
  citationLine,
  avatarUrl,
  voiceoverUrl,
  totalSeconds,
}) => {
  const { fps, width, height } = useVideoConfig();
  const totalFrames = Math.ceil(totalSeconds * fps);

  const hookSeconds = Math.max(1.6, Math.min(3, totalSeconds * 0.1));
  const ctaSeconds = Math.max(2, Math.min(4, totalSeconds * 0.12));
  const bodySeconds = scenes.reduce((acc, s) => acc + s.seconds, 0) || 1;
  const bodyScale = (totalSeconds - hookSeconds - ctaSeconds) / bodySeconds;

  let cursor = 0;
  const hookRange = { from: 0, durationInFrames: Math.round(hookSeconds * fps) };
  cursor += hookRange.durationInFrames;
  const sceneRanges = scenes.map((s) => {
    const dur = Math.max(1, Math.round(s.seconds * bodyScale * fps));
    const r = { from: cursor, durationInFrames: dur };
    cursor += dur;
    return r;
  });
  const ctaRange = {
    from: cursor,
    durationInFrames: Math.max(1, totalFrames - cursor),
  };

  return (
    <AbsoluteFill
      style={{ backgroundColor: BRAND.bg, color: BRAND.ink, fontFamily: BRAND.fontSans }}
    >
      {/* Persistent radio-booth background. Renders first so everything else stacks on top. */}
      <RadioBoothBg width={width} height={height} />

      {/* Avatar plays the entire duration MUTED. Each scene Sequence may
          overlay stock B-roll on top of it; the avatar continues
          underneath so cutaways feel like a director cutting away from
          the host, not stopping her. */}
      {avatarUrl && (
        <AvatarFrame avatarUrl={avatarUrl} />
      )}

      {/* Hook scene: text overlay, avatar visible underneath. */}
      <Sequence from={hookRange.from} durationInFrames={hookRange.durationInFrames}>
        <CaptionLayer text={hook} kind="hook" />
      </Sequence>

      {/* Body scenes: each one is text overlay + optional B-roll cutaway. */}
      {scenes.map((s, i) => (
        <Sequence
          key={i}
          from={sceneRanges[i].from}
          durationInFrames={sceneRanges[i].durationInFrames}
        >
          {s.clips[0] && (
            <CutawayBroll clip={s.clips[0]} />
          )}
          <CaptionLayer text={s.text} kind="body" />
          {s.clips[0]?.attribution && (
            <AttributionPill text={s.clips[0].attribution} />
          )}
        </Sequence>
      ))}

      {/* CTA: text overlay, avatar visible again. */}
      <Sequence from={ctaRange.from} durationInFrames={ctaRange.durationInFrames}>
        <CaptionLayer text={cta} kind="cta" />
      </Sequence>

      {citationLine && <CitationStrip text={citationLine} />}
      <Watermark />

      {/* Voiceover is the primary audio track — independent of avatar
          video so it keeps playing during B-roll cutaways. */}
      {voiceoverUrl && <Audio src={voiceoverUrl} />}
    </AbsoluteFill>
  );
};

/* -------------------------- avatar + B-roll layers -------------------------- */

const AvatarFrame: React.FC<{ avatarUrl: string }> = ({ avatarUrl }) => (
  <AbsoluteFill
    style={{
      top: AVATAR_AREA_TOP,
      height: AVATAR_AREA_HEIGHT,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    }}
  >
    <OffthreadVideo
      src={avatarUrl}
      muted
      style={{
        // Hallo emits a square video matching the portrait aspect.
        // Scale to fill the available width and let the natural
        // square height (1080 at width 1080) sit in the centre of
        // the 1248px tall area — leaves a small breathing strip
        // above + below the head.
        width: 1080,
        height: 1080,
        objectFit: "cover",
        borderRadius: 0,
      }}
    />
    {/* Soft top + bottom fade so the avatar blends into the booth bg. */}
    <AbsoluteFill
      style={{
        pointerEvents: "none",
        background:
          "linear-gradient(180deg, rgba(16,17,21,0.45) 0%, rgba(16,17,21,0) 18%, rgba(16,17,21,0) 80%, rgba(16,17,21,0.55) 100%)",
      }}
    />
  </AbsoluteFill>
);

const CutawayBroll: React.FC<{ clip: StockSceneClip }> = ({ clip }) => (
  <AbsoluteFill>
    <OffthreadVideo
      src={clip.url}
      muted
      style={{
        width: "100%",
        height: "100%",
        objectFit: "cover",
      }}
    />
    {/* Same dark vignette as StockReel so captions stay readable on the cutaway. */}
    <AbsoluteFill
      style={{
        background:
          "linear-gradient(180deg, rgba(16,17,21,0.55) 0%, rgba(16,17,21,0.15) 35%, rgba(16,17,21,0.20) 65%, rgba(16,17,21,0.75) 100%)",
      }}
    />
  </AbsoluteFill>
);

/* --------------------------- text / chrome layers --------------------------- */

const CaptionLayer: React.FC<{ text: string; kind: "hook" | "body" | "cta" }> = ({
  text,
  kind,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const enter = spring({ fps, frame, config: { damping: 200 } });
  const opacity = interpolate(enter, [0, 1], [0, 1]);
  const translateY = interpolate(enter, [0, 1], [16, 0]);

  // Text lives in the upper 35% of the frame (above the avatar). For
  // the hook and CTA we lean larger + warmer; for body scenes a tighter
  // serif treatment that reads as "captioned thought" rather than
  // shouty.
  const fontSize = kind === "hook" ? 84 : kind === "cta" ? 72 : 56;
  const weight = kind === "hook" ? 700 : kind === "cta" ? 600 : 500;
  const color =
    kind === "hook" ? BRAND.warm : kind === "cta" ? BRAND.teal : BRAND.ink;

  return (
    <AbsoluteFill
      style={{
        height: AVATAR_AREA_TOP, // upper band only
        alignItems: "center",
        justifyContent: "center",
        paddingLeft: SAFE_AREA.side,
        paddingRight: SAFE_AREA.side,
        paddingTop: SAFE_AREA.top,
      }}
    >
      <div
        style={{
          opacity,
          transform: `translateY(${translateY}px)`,
          fontFamily: BRAND.fontSerif,
          fontSize,
          fontWeight: weight,
          color,
          lineHeight: 1.18,
          textAlign: "center",
          textWrap: "balance" as React.CSSProperties["textWrap"],
          maxWidth: 920,
          textShadow: "0 4px 24px rgba(0,0,0,0.55)",
        }}
      >
        {text}
      </div>
    </AbsoluteFill>
  );
};

const RadioBoothBg: React.FC<{ width: number; height: number }> = ({ width, height }) => {
  const frame = useCurrentFrame();
  const drift = (period: number) => Math.sin((frame / period) * Math.PI * 2);
  // Warm-amber pools to evoke a single side-light on a dark booth wall.
  // We deliberately avoid the existing StockReel teal/plum mix here so
  // the avatar reel reads as visually distinct from the typography reel.
  const pool = (cx: number, cy: number, r: number, color: string, period: number) => (
    <div
      style={{
        position: "absolute",
        left: cx - r,
        top: cy - r,
        width: r * 2,
        height: r * 2,
        borderRadius: "50%",
        background: `radial-gradient(circle at 35% 35%, ${color}aa, transparent 70%)`,
        filter: "blur(80px)",
        transform: `translate(${drift(period) * 28}px, ${drift(period * 1.4) * 22}px)`,
      }}
    />
  );
  return (
    <AbsoluteFill style={{ backgroundColor: BRAND.bg }}>
      {pool(width * 0.85, height * 0.15, 420, BRAND.warm, 280)}
      {pool(width * 0.15, height * 0.85, 360, BRAND.plum, 340)}
    </AbsoluteFill>
  );
};

const AttributionPill: React.FC<{ text: string }> = ({ text }) => (
  <div
    style={{
      position: "absolute",
      right: 32,
      top: 32,
      padding: "8px 14px",
      fontSize: 18,
      color: BRAND.inkMuted,
      background: "rgba(16,17,21,0.55)",
      borderRadius: 10,
    }}
  >
    {text}
  </div>
);

const CitationStrip: React.FC<{ text: string }> = ({ text }) => (
  <div
    style={{
      position: "absolute",
      left: 48,
      right: 48,
      bottom: 110,
      textAlign: "center",
      color: BRAND.inkMuted,
      fontSize: 26,
      lineHeight: 1.4,
      textShadow: "0 2px 12px rgba(0,0,0,0.6)",
    }}
  >
    {text}
  </div>
);

const Watermark: React.FC = () => (
  <div
    style={{
      position: "absolute",
      left: 48,
      bottom: 48,
      display: "flex",
      alignItems: "center",
      gap: 14,
      color: BRAND.inkMuted,
      fontSize: 26,
      textShadow: "0 2px 12px rgba(0,0,0,0.6)",
    }}
  >
    <span
      style={{
        display: "grid",
        placeItems: "center",
        width: 44,
        height: 44,
        borderRadius: 12,
        background: `linear-gradient(120deg, ${BRAND.plum}, ${BRAND.warm} 60%, ${BRAND.teal})`,
        color: "#fff",
        fontWeight: 600,
      }}
    >
      {"\u25D0"}
    </span>
    {BRAND.watermark} · {BRAND.watermarkSuffix}
  </div>
);
