export const DISCLAIMERS = {
  educational:
    "This site is for education and exploration only. It does not provide medical, psychological, or therapeutic advice and is not a substitute for a licensed clinician.",

  ageGate:
    "This site discusses sexual health, sexuality, and intimate relationships in clinical detail. You must be 18 or older to enter.",

  ai: "Replies are generated by AI grounded in the curated library. Citations are shown for every claim. The AI can be wrong and is not a clinician.",

  sahay:
    "Sahay is an AI companion trained on evidence-based sex-therapy literature. Sahay is not a licensed therapist and is not a replacement for one. What you share stays encrypted and private.",

  copyright:
    "We do not host copyrighted books or paywalled articles. For copyrighted works we provide curator notes, short fair-use quotes with citations, and links to authorized publishers and libraries.",
} as const;

export type DisclaimerKey = keyof typeof DISCLAIMERS;
